FROM golang:1.22-alpine3.19

WORKDIR /demo

COPY . .
RUN go mod download
RUN ls -l
RUN CGO_ENABLED=0 GOOS=linux go build  -o app ./internal_service/main.go

RUN chmod +x ./app

EXPOSE 8080

CMD ["./app"]