# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: LokiDemo
    type: loki
    uid: loki
    url: http://loki_read:3100
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeout: 10
      maxLines: 500
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "tenant1"