version: '3.9'
x-default-logging: &logging
  driver: "fluentd"
  options:
    fluentd-async-connect: "true"
    fluentd-address: "localhost:24224"
    tag: "{{.Name}}"

networks:
  default:
    name: ironman-demo
    driver: bridge

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./infrastructure/otelcollector/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      #- 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      #- 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  # Loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./infrastructure/loki/loki.yml:/etc/loki/local-config.yml
    ports:
      - "3100:3100"

  # Tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4327:4317"  # otlp grpc
      - "4328:4318"  # otlp http