FROM node:20.10.0-alpine AS base-image
RUN mkdir /app
WORKDIR /app
COPY ./src package.json pnpm-lock.yaml tsconfig.build.json tsconfig.json ./
RUN npm i -g pnpm
RUN pnpm install
RUN pnpm build 
FROM node:20.10.0-alpine AS production-image
RUN mkdir /app
WORKDIR /app
COPY --from=base-image app/dist app/package.json app/pnpm-lock.yaml ./
RUN npm i -g pnpm
RUN pnpm install --prod
EXPOSE 3000
ENTRYPOINT [ "node", "./dist/main" ]
