# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otelcol:4317
      http:
        endpoint: otelcol:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: "0.0.0.0:9090"
    namespace: demo
    enable_open_metrics: true

  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [ debug, otlp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug,prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug]
