# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: TraceDemo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: 'loki'
        tags: 
          - key: app
        filterByTraceID: true
        spanEndTimeShift: 5m
        spanStartTimeShift: '-5m'
      serviceMap:
        httpMethod: GET
        datasourceUid: 'prometheus'
      tracesToMetrics:
        datasourceUid: prometheus
        queries:
          - name: 每分鐘錯誤數
            query: >-
              sum(rate(traces_spanmetrics_latency_count{$$__tags , status_code="STATUS_CODE_ERROR"}[1m])*60)
              by(service, span_name)
          - name: PR95持續時間
            query: >-
              histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[1m])) by (le, service, http_target, http_method))
          - name: 該服務的QPS
            query: >-
              sum(rate(traces_spanmetrics_calls_total{ $$__tags }[1m])*60 ) by (service, http_target)
        spanEndTimeShift: 10m
        spanStartTimeShift: '-10m'
        tags:
          - key: service.name
            value: service
          - key: http.target
            value: http_target
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    editable: true
    jsonData:
        httpMethod: GET
        exemplarTraceIdDestinations:
          - name: trace_id
            datasourceUid: tempo